header = Register
email-label = E-Mail
email-hint = E-mail address
email-inv = Invalid e-mail address
username-label = Username
username-hint = Username (4-32 characters, allowed characters: a-zA-Z0-9_)
username-inv = Invalid username (4-32 characters, allowed characters: a-zA-Z0-9_)
password-label = Password
password-hint = Password (6-32 characters, allowed characters: a-zA-Z0-9_)
password-inv = Invalid password (6-32 characters, allowed characters: a-zA-Z0-9_)
password2-label = Password (twice)
password2-hint = Password (must be the same as above)
password2-inv = Password is different from above
error-label = Failed to register: { $details }
error-net = Net error
error-unknown = Unknown error
error-dup-email = This e-mail address has been registered
error-dup-username = The username has been used
error-email = Invalid e-mail address
error-username = Invalid username
error-password = Invalid passwor
error-password2 = The 2 passwords are different
button-register = Register
button-login = Login