header = 注册
email-label = 邮箱
email-hint = 账号邮箱地址
email-inv = 邮箱地址格式有误
username-label = 用户名
username-hint = 用户名（4-32 个字符，且仅允许以下字符：a-zA-Z0-9_）
username-inv = 用户名不合要求（4-32 个字符，且仅允许以下字符：a-zA-Z0-9_）
password-label = 密码
password-hint = 密码（6-32 个字符，且仅允许以下字符：a-zA-Z0-9_）
password-inv = 密码不符合要求（6-32 个字符，且仅允许以下字符：a-zA-Z0-9_）
password2-label = 重复输入密码
password2-hint = 重复输入密码（必须和上一栏相同）
password2-inv = 与上一栏密码不同
error-label = 注册失败：{ $details }
error-net = 网络错误
error-unknown = 未知错误
error-dup-email = 该邮箱地址已被注册
error-dup-username = 该用户名已被使用
error-email = 邮箱地址格式有误
error-username = 用户名不合要求
error-password = 密码不合要求
error-password2 = 两次密码不同
button-register = 注册
button-login = 登录