header = 主页
welcome = { $username }（{ $email }），您好！
id-label = 设备 ID
id-hint = 要添加的设备 ID
button-add = 添加设备
button-fetch = 刷新设备
button-logout = 登出
button-edit = 编辑
button-details = 详情
button-delete = 删除
device-stat = { $total } 条信息，{ $alert } 条存在警告
error-label = 错误：{ $details }
error-net = 网络错误
error-unknown = 未知错误
error-no-device = 该设备不存在
error-no-user = 该用户不存在