header = Edit Device Information
id-label = Device ID
name-label = Device Name
name-hint = Device name (4-32 characters, allowed characters: a-zA-Z0-9_ and space)
name-inv = Invalid device name (4-32 characters, allowed characters: a-zA-Z0-9_ and space)
desc-label = Device Description
desc-hint = Device description (at most 256 characters)
success-info = Device information is modified successfully
error-label = Failed to modify: { $details }
error-net = Net error
error-unknown = Unknown error
error-no-device = Device doesn't exist
error-name = Invalid device name
button-save = Save
button-home = Go Back to Home
